source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'capybara', '3.5.1'
gem 'rspec', '3.8.0'
gem 'selenium-webdriver', '3.14.0'
gem 'cucumber', '3.1.2'
gem 'xpath'
gem 'site_prism', '2.16'

